/**
 * Leerstof voor Svenska Kat: 160 items (5 werelden x 8 challenges x 4 nieuwe items) en de rijtjes voor Beuken.
 * Betekenisvelden: binnen een challenge (world + slot) komen de 4 items uit 4 verschillende velden.
 */

export const ITEMS = [
    {
        id: 'vt-n-01',
        world: 'volkstuin',
        slot: 1,
        kind: 'noun',
        field: 'tuin',
        level: 1,
        nl: 'de volkstuin',
        sv: 'kolonilott',
        article: 'en',
        definite: 'kolonilotten',
        plural: 'kolonilotter',
        why: 'Kolonilott is een en-woord.',
        accept: []
    },
    {
        id: 'vt-n-02',
        world: 'volkstuin',
        slot: 1,
        kind: 'noun',
        field: 'dieren',
        level: 1,
        nl: 'de kat',
        sv: 'katt',
        article: 'en',
        definite: 'katten',
        plural: 'katter',
        why: 'Katt is een en-woord.',
        accept: []
    },
    {
        id: 'vt-w-01',
        world: 'volkstuin',
        slot: 1,
        kind: 'word',
        field: 'werkwoord',
        level: 1,
        nl: 'zijn',
        sv: 'att vara',
        forms: { presens: 'är', preteritum: 'var', supinum: 'varit' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor. Vara is onregelmatig: är, var, varit.',
        accept: []
    },
    {
        id: 'vt-p-01',
        world: 'volkstuin',
        slot: 1,
        kind: 'phrase',
        field: 'voornaamwoord',
        level: 1,
        nl: 'Cleo en ik zijn hier.',
        sv: 'Cleo och jag är här.',
        why: 'Är betekent "ben, is, zijn" en blijft voor iedereen hetzelfde. Zeg eerst de ander, dan jag.',
        accept: ['Jag och Cleo är här.']
    },
    {
        id: 'vt-n-03',
        world: 'volkstuin',
        slot: 2,
        kind: 'noun',
        field: 'gereedschap',
        level: 1,
        nl: 'de spade',
        sv: 'spade',
        article: 'en',
        definite: 'spaden',
        plural: 'spadar',
        why: 'Spade is een en-woord.',
        accept: []
    },
    {
        id: 'vt-w-02',
        world: 'volkstuin',
        slot: 2,
        kind: 'word',
        field: 'bezit',
        level: 1,
        nl: 'hebben',
        sv: 'att ha',
        forms: { presens: 'har', preteritum: 'hade', supinum: 'haft' },
        why: 'Har is hebben en blijft hetzelfde voor jag, du, han en vi.',
        accept: []
    },
    {
        id: 'vt-g-01',
        world: 'volkstuin',
        slot: 2,
        kind: 'gap',
        field: 'grammatica',
        level: 1,
        nl: 'Cleo is een kat.',
        sv: 'Cleo ___ en katt.',
        answer: 'är',
        why: 'Är is "is" en verandert niet per persoon.',
        accept: []
    },
    {
        id: 'vt-s-01',
        world: 'volkstuin',
        slot: 2,
        kind: 'silly',
        field: 'humor',
        level: 1,
        nl: 'De kat is een volkstuin.',
        sv: 'Katten är en kolonilott.',
        why: 'Een gekke zin met woorden die je al kent. Katten is de bepaalde vorm van en katt.',
        accept: []
    },
    {
        id: 'vt-n-04',
        world: 'volkstuin',
        slot: 3,
        kind: 'noun',
        field: 'eten',
        level: 1,
        nl: 'de tomaat',
        sv: 'tomat',
        article: 'en',
        definite: 'tomaten',
        plural: 'tomater',
        why: 'Tomat is een en-woord.',
        accept: []
    },
    {
        id: 'vt-n-05',
        world: 'volkstuin',
        slot: 3,
        kind: 'noun',
        field: 'dieren',
        level: 1,
        nl: 'de slak',
        sv: 'snigel',
        article: 'en',
        definite: 'snigeln',
        plural: 'sniglar',
        why: 'Snigel is een en-woord. Het meervoud sniglar laat de laatste e weg.',
        accept: []
    },
    {
        id: 'vt-f-01',
        world: 'volkstuin',
        slot: 3,
        kind: 'form',
        field: 'grammatica',
        level: 1,
        nl: 'en tomat, bepaald',
        prompt: 'en tomat, bepaald',
        answer: 'tomaten',
        why: 'Bij een en-woord komt -en achter het woord: tomaten.',
        accept: []
    },
    {
        id: 'vt-p-02',
        world: 'volkstuin',
        slot: 3,
        kind: 'phrase',
        field: 'voornaamwoord',
        level: 1,
        nl: 'Jij hebt een tomaat en ik heb een spade.',
        sv: 'Du har en tomat och jag har en spade.',
        why: 'Har blijft har, ook bij du en jag.',
        accept: []
    },
    {
        id: 'vt-n-06',
        world: 'volkstuin',
        slot: 4,
        kind: 'noun',
        field: 'gereedschap',
        level: 1,
        nl: 'de gieter',
        sv: 'vattenkanna',
        article: 'en',
        definite: 'vattenkannan',
        plural: 'vattenkannor',
        why: 'Vattenkanna is een en-woord.',
        accept: []
    },
    {
        id: 'vt-n-07',
        world: 'volkstuin',
        slot: 4,
        kind: 'noun',
        field: 'planten',
        level: 1,
        nl: 'de bloem',
        sv: 'blomma',
        article: 'en',
        definite: 'blomman',
        plural: 'blommor',
        why: 'Blomma is een en-woord. Bij en-woorden op -a wordt het meervoud -or: blommor.',
        accept: []
    },
    {
        id: 'vt-w-03',
        world: 'volkstuin',
        slot: 4,
        kind: 'word',
        field: 'tuinwerk',
        level: 1,
        nl: 'water geven (aan planten)',
        sv: 'att vattna',
        forms: { presens: 'vattnar', preteritum: 'vattnade', supinum: 'vattnat' },
        why: 'Het werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'vt-g-02',
        world: 'volkstuin',
        slot: 4,
        kind: 'gap',
        field: 'grammatica',
        level: 1,
        nl: 'Jacob heeft een gieter.',
        sv: 'Jacob ___ en vattenkanna.',
        answer: 'har',
        why: 'Har is hebben. Het werkwoord verandert niet per persoon.',
        accept: []
    },
    {
        id: 'vt-n-08',
        world: 'volkstuin',
        slot: 5,
        kind: 'noun',
        field: 'kleding',
        level: 1,
        nl: 'de laars',
        sv: 'stövel',
        article: 'en',
        definite: 'stöveln',
        plural: 'stövlar',
        why: 'Stövel is een en-woord. Het meervoud laat de e weg: stövlar.',
        accept: []
    },
    {
        id: 'vt-n-09',
        world: 'volkstuin',
        slot: 5,
        kind: 'noun',
        field: 'weer',
        level: 1,
        nl: 'de zon',
        sv: 'sol',
        article: 'en',
        definite: 'solen',
        plural: 'solar',
        why: 'Sol is een en-woord.',
        accept: []
    },
    {
        id: 'vt-b-01',
        world: 'volkstuin',
        slot: 5,
        kind: 'builder',
        field: 'zinnen',
        level: 1,
        nl: 'Waar is Cleo nu?',
        sv: 'Var är Cleo nu?',
        pieces: ['Var', 'är', 'Cleo', 'nu?'],
        why: 'Bij een vraag met een vraagwoord komt het werkwoord op de tweede plek.',
        accept: []
    },
    {
        id: 'vt-w-04',
        world: 'volkstuin',
        slot: 5,
        kind: 'word',
        field: 'tuinwerk',
        level: 1,
        nl: 'plukken',
        sv: 'att plocka',
        forms: { presens: 'plockar', preteritum: 'plockade', supinum: 'plockat' },
        why: 'Het werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'vt-n-10',
        world: 'volkstuin',
        slot: 6,
        kind: 'noun',
        field: 'natuur',
        level: 1,
        nl: 'de boom',
        sv: 'träd',
        article: 'ett',
        definite: 'trädet',
        plural: 'träd',
        why: 'Träd is een ett-woord. Het meervoud is hetzelfde: ett träd, flera träd.',
        accept: []
    },
    {
        id: 'vt-w-05',
        world: 'volkstuin',
        slot: 6,
        kind: 'word',
        field: 'rust',
        level: 1,
        nl: 'slapen',
        sv: 'att sova',
        forms: { presens: 'sover', preteritum: 'sov', supinum: 'sovit' },
        why: 'Sova is onregelmatig in de verleden tijd: sov.',
        accept: []
    },
    {
        id: 'vt-s-02',
        world: 'volkstuin',
        slot: 6,
        kind: 'silly',
        field: 'humor',
        level: 1,
        nl: 'De slak plukt een laars.',
        sv: 'Snigeln plockar en stövel.',
        why: 'Een gekke zin met bekende woorden. Snigeln is de bepaalde vorm van en snigel.',
        accept: []
    },
    {
        id: 'vt-p-03',
        world: 'volkstuin',
        slot: 6,
        kind: 'phrase',
        field: 'weer',
        level: 1,
        nl: 'Cleo slaapt in de zon.',
        sv: 'Cleo sover i solen.',
        why: 'Solen is de bepaalde vorm van en sol: de zon. Het werkwoord sover is voor iedereen hetzelfde.',
        accept: []
    },
    {
        id: 'vt-n-11',
        world: 'volkstuin',
        slot: 7,
        kind: 'noun',
        field: 'dieren',
        level: 1,
        nl: 'de bij',
        sv: 'bi',
        article: 'ett',
        definite: 'biet',
        plural: 'bin',
        why: 'Bi is een ett-woord. Het meervoud is bin.',
        accept: []
    },
    {
        id: 'vt-w-06',
        world: 'volkstuin',
        slot: 7,
        kind: 'word',
        field: 'eten',
        level: 1,
        nl: 'eten (werkwoord)',
        sv: 'att äta',
        forms: { presens: 'äter', preteritum: 'åt', supinum: 'ätit' },
        why: 'Äta is onregelmatig in de verleden tijd: åt.',
        accept: []
    },
    {
        id: 'vt-g-03',
        world: 'volkstuin',
        slot: 7,
        kind: 'gap',
        field: 'grammatica',
        level: 1,
        nl: 'Wij hebben een volkstuin.',
        sv: 'Vi ___ en kolonilott.',
        answer: 'har',
        why: 'Ook bij vi blijft het werkwoord har.',
        accept: []
    },
    {
        id: 'vt-f-02',
        world: 'volkstuin',
        slot: 7,
        kind: 'form',
        field: 'tijd',
        level: 1,
        nl: 'att vattna, verleden tijd',
        prompt: 'att vattna, verleden tijd',
        answer: 'vattnade',
        why: 'Bij werkwoorden zoals vattna komt -de in de verleden tijd: vattnade.',
        accept: []
    },
    {
        id: 'vt-n-12',
        world: 'volkstuin',
        slot: 8,
        kind: 'noun',
        field: 'huis',
        level: 1,
        nl: 'het huisje',
        sv: 'stuga',
        article: 'en',
        definite: 'stugan',
        plural: 'stugor',
        why: 'Stuga is een en-woord. Bij en-woorden op -a wordt het meervoud -or: stugor.',
        accept: []
    },
    {
        id: 'vt-n-13',
        world: 'volkstuin',
        slot: 8,
        kind: 'noun',
        field: 'eten',
        level: 1,
        nl: 'de wortel',
        sv: 'morot',
        article: 'en',
        definite: 'moroten',
        plural: 'morötter',
        why: 'Morot is een en-woord. Het meervoud krijgt een umlaut: morötter.',
        accept: []
    },
    {
        id: 'vt-p-04',
        world: 'volkstuin',
        slot: 8,
        kind: 'phrase',
        field: 'negatie',
        level: 1,
        nl: 'Cleo eet geen tomaten.',
        sv: 'Cleo äter inte tomater.',
        why: 'In een hoofdzin staat inte na het werkwoord: äter inte.',
        accept: ['Cleo äter inga tomater.']
    },
    {
        id: 'vt-g-04',
        world: 'volkstuin',
        slot: 8,
        kind: 'gap',
        field: 'verbinding',
        level: 1,
        nl: 'Ik heb een spade en jij hebt een gieter.',
        sv: 'Jag har en spade ___ du har en vattenkanna.',
        answer: 'och',
        why: 'Och betekent "en" en verbindt twee delen van een zin.',
        accept: []
    },
    {
        id: 'ca-n-01',
        world: 'camper',
        slot: 1,
        kind: 'noun',
        field: 'vervoer',
        level: 1,
        nl: 'de camper',
        sv: 'husbil',
        article: 'en',
        definite: 'husbilen',
        plural: 'husbilar',
        why: 'Husbil is een en-woord.',
        accept: []
    },
    {
        id: 'ca-n-02',
        world: 'camper',
        slot: 1,
        kind: 'noun',
        field: 'reizen',
        level: 1,
        nl: 'de kaart (landkaart)',
        sv: 'karta',
        article: 'en',
        definite: 'kartan',
        plural: 'kartor',
        why: 'Karta is een en-woord. Bij en-woorden op -a wordt het meervoud -or: kartor.',
        accept: []
    },
    {
        id: 'ca-w-01',
        world: 'camper',
        slot: 1,
        kind: 'word',
        field: 'werkwoord',
        level: 1,
        nl: 'rijden (zelf achter het stuur)',
        sv: 'att köra',
        forms: { presens: 'kör', preteritum: 'körde', supinum: 'kört' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'ca-p-01',
        world: 'camper',
        slot: 1,
        kind: 'phrase',
        field: 'huis',
        level: 1,
        nl: 'Cleo slaapt in de camper.',
        sv: 'Cleo sover i husbilen.',
        why: 'Husbilen is de bepaalde vorm van en husbil: de camper.',
        accept: []
    },
    {
        id: 'ca-n-03',
        world: 'camper',
        slot: 2,
        kind: 'noun',
        field: 'kamperen',
        level: 1,
        nl: 'de tent',
        sv: 'tält',
        article: 'ett',
        definite: 'tältet',
        plural: 'tält',
        why: 'Tält is een ett-woord. Het meervoud is hetzelfde: ett tält, flera tält.',
        accept: []
    },
    {
        id: 'ca-w-02',
        world: 'camper',
        slot: 2,
        kind: 'word',
        field: 'beweging',
        level: 1,
        nl: 'gaan (met een voertuig)',
        sv: 'att åka',
        forms: { presens: 'åker', preteritum: 'åkte', supinum: 'åkt' },
        why: 'Åka gebruik je als je met een auto, trein of bus ergens heen gaat.',
        accept: []
    },
    {
        id: 'ca-g-01',
        world: 'camper',
        slot: 2,
        kind: 'gap',
        field: 'bestemming',
        level: 1,
        nl: 'We rijden naar Malmö.',
        sv: 'Vi ___ till Malmö.',
        answer: 'åker',
        why: 'Åka gebruik je voor reizen met een voertuig. De vorm åker is voor iedereen hetzelfde.',
        accept: ['kör']
    },
    {
        id: 'ca-s-01',
        world: 'camper',
        slot: 2,
        kind: 'silly',
        field: 'humor',
        level: 1,
        nl: 'De kat rijdt de camper naar de volkstuin.',
        sv: 'Katten kör husbilen till kolonilotten.',
        why: 'Een gekke zin met bekende woorden. De zelfstandige naamwoorden staan in de bepaalde vorm: katten, husbilen, kolonilotten.',
        accept: []
    },
    {
        id: 'ca-n-04',
        world: 'camper',
        slot: 3,
        kind: 'noun',
        field: 'slapen',
        level: 1,
        nl: 'het bed',
        sv: 'säng',
        article: 'en',
        definite: 'sängen',
        plural: 'sängar',
        why: 'Säng is een en-woord.',
        accept: []
    },
    {
        id: 'ca-n-05',
        world: 'camper',
        slot: 3,
        kind: 'noun',
        field: 'weg',
        level: 1,
        nl: 'de weg',
        sv: 'väg',
        article: 'en',
        definite: 'vägen',
        plural: 'vägar',
        why: 'Väg is een en-woord.',
        accept: []
    },
    {
        id: 'ca-f-01',
        world: 'camper',
        slot: 3,
        kind: 'form',
        field: 'grammatica',
        level: 1,
        nl: 'en husbil, meervoud',
        prompt: 'en husbil, meervoud',
        answer: 'husbilar',
        why: 'De meeste en-woorden krijgen -ar in het meervoud: husbilar.',
        accept: []
    },
    {
        id: 'ca-p-02',
        world: 'camper',
        slot: 3,
        kind: 'phrase',
        field: 'mensen',
        level: 1,
        nl: 'Jacob rijdt en ik heb de kaart.',
        sv: 'Jacob kör och jag har kartan.',
        why: 'Kartan is de bepaalde vorm van en karta. Kör en har zijn voor iedereen hetzelfde.',
        accept: []
    },
    {
        id: 'ca-n-06',
        world: 'camper',
        slot: 4,
        kind: 'noun',
        field: 'voorwerp',
        level: 1,
        nl: 'de sleutel',
        sv: 'nyckel',
        article: 'en',
        definite: 'nyckeln',
        plural: 'nycklar',
        why: 'Nyckel is een en-woord. Het meervoud laat de e weg: nycklar.',
        accept: []
    },
    {
        id: 'ca-w-03',
        world: 'camper',
        slot: 4,
        kind: 'word',
        field: 'stilstaan',
        level: 1,
        nl: 'stoppen',
        sv: 'att stanna',
        forms: { presens: 'stannar', preteritum: 'stannade', supinum: 'stannat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'ca-g-02',
        world: 'camper',
        slot: 4,
        kind: 'gap',
        field: 'voorzetsel',
        level: 1,
        nl: 'Cleo slaapt in de camper.',
        sv: 'Cleo sover ___ husbilen.',
        answer: 'i',
        why: '"I" betekent "in" en gebruik je voor plekken waar je binnen bent.',
        accept: []
    },
    {
        id: 'ca-t-01',
        world: 'camper',
        slot: 4,
        kind: 'truefalse',
        field: 'reizen',
        level: 1,
        nl: 'We rijden met de camper naar Malmö.',
        sv: 'Vi åker till Malmö med husbilen.',
        isTrue: true,
        correction: null,
        why: 'Med betekent "met". Åker till is "gaan naar".',
        accept: []
    },
    {
        id: 'ca-n-07',
        world: 'camper',
        slot: 5,
        kind: 'noun',
        field: 'beddengoed',
        level: 1,
        nl: 'de deken',
        sv: 'filt',
        article: 'en',
        definite: 'filten',
        plural: 'filtar',
        why: 'Filt is een en-woord.',
        accept: []
    },
    {
        id: 'ca-n-08',
        world: 'camper',
        slot: 5,
        kind: 'noun',
        field: 'keuken',
        level: 1,
        nl: 'de koelkast',
        sv: 'kylskåp',
        article: 'ett',
        definite: 'kylskåpet',
        plural: 'kylskåp',
        why: 'Kylskåp is een ett-woord. Het meervoud is hetzelfde: ett kylskåp, flera kylskåp.',
        accept: []
    },
    {
        id: 'ca-b-01',
        world: 'camper',
        slot: 5,
        kind: 'builder',
        field: 'woordvolgorde',
        level: 1,
        nl: 'Vandaag rijden we naar Malmö.',
        sv: 'Idag åker vi till Malmö.',
        pieces: ['Idag', 'åker', 'vi', 'till', 'Malmö.'],
        why: 'Het werkwoord staat altijd op de tweede plek. Begin je met idag, dan komt åker voor vi.',
        accept: [
            'Vi åker till Malmö idag.',
            'I dag åker vi till Malmö.',
            'Vi åker till Malmö i dag.'
        ]
    },
    {
        id: 'ca-w-04',
        world: 'camper',
        slot: 5,
        kind: 'word',
        field: 'eigenschap',
        level: 1,
        nl: 'krap',
        sv: 'trång',
        why: 'Bij een ett-woord krijgt trång een -t: ett trångt tält.',
        accept: []
    },
    {
        id: 'ca-n-09',
        world: 'camper',
        slot: 6,
        kind: 'noun',
        field: 'natuur',
        level: 1,
        nl: 'het bos',
        sv: 'skog',
        article: 'en',
        definite: 'skogen',
        plural: 'skogar',
        why: 'Skog is een en-woord.',
        accept: []
    },
    {
        id: 'ca-w-05',
        world: 'camper',
        slot: 6,
        kind: 'word',
        field: 'bagage',
        level: 1,
        nl: 'inpakken',
        sv: 'att packa',
        forms: { presens: 'packar', preteritum: 'packade', supinum: 'packat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'ca-s-02',
        world: 'camper',
        slot: 6,
        kind: 'silly',
        field: 'humor',
        level: 1,
        nl: 'De slak slaapt in de koelkast.',
        sv: 'Snigeln sover i kylskåpet.',
        why: 'Een gekke zin met bekende woorden. Kylskåpet is de bepaalde vorm van ett kylskåp.',
        accept: []
    },
    {
        id: 'ca-p-03',
        world: 'camper',
        slot: 6,
        kind: 'phrase',
        field: 'reizen',
        level: 1,
        nl: 'We pakken de tent en de kaart in.',
        sv: 'Vi packar tältet och kartan.',
        why: 'Tältet en kartan zijn bepaalde vormen: ett tält wordt tältet, en karta wordt kartan.',
        accept: []
    },
    {
        id: 'ca-n-10',
        world: 'camper',
        slot: 7,
        kind: 'noun',
        field: 'verkeer',
        level: 2,
        nl: 'het tankstation',
        sv: 'bensinstation',
        article: 'en',
        definite: 'bensinstationen',
        plural: 'bensinstationer',
        why: 'Bensinstation is een en-woord. Station is een en-woord, dus bensinstation ook. Het meervoud krijgt -er.',
        accept: []
    },
    {
        id: 'ca-w-06',
        world: 'camper',
        slot: 7,
        kind: 'word',
        field: 'drinken',
        level: 2,
        nl: 'een koffiepauze nemen (fika)',
        sv: 'att fika',
        forms: { presens: 'fikar', preteritum: 'fikade', supinum: 'fikat' },
        why: 'Fika is in Zweden een vast ritueel: koffie met iets lekkers.',
        accept: []
    },
    {
        id: 'ca-g-03',
        world: 'camper',
        slot: 7,
        kind: 'gap',
        field: 'bijvoeglijk naamwoord',
        level: 2,
        nl: 'De tent is krap.',
        sv: 'Tältet är ___.',
        answer: 'trångt',
        why: 'Tält is een ett-woord, dus trång wordt trångt.',
        accept: []
    },
    {
        id: 'ca-f-02',
        world: 'camper',
        slot: 7,
        kind: 'form',
        field: 'tijd',
        level: 2,
        nl: 'att köra, verleden tijd',
        prompt: 'att köra, verleden tijd',
        answer: 'körde',
        why: 'Köra krijgt -de in de verleden tijd: körde.',
        accept: []
    },
    {
        id: 'ca-n-11',
        world: 'camper',
        slot: 8,
        kind: 'noun',
        field: 'meer',
        level: 2,
        nl: 'het meer',
        sv: 'sjö',
        article: 'en',
        definite: 'sjön',
        plural: 'sjöar',
        why: 'Sjö is een en-woord.',
        accept: []
    },
    {
        id: 'ca-n-12',
        world: 'camper',
        slot: 8,
        kind: 'noun',
        field: 'keuken',
        level: 2,
        nl: 'het kopje',
        sv: 'kopp',
        article: 'en',
        definite: 'koppen',
        plural: 'koppar',
        why: 'Kopp is een en-woord.',
        accept: []
    },
    {
        id: 'ca-p-04',
        world: 'camper',
        slot: 8,
        kind: 'phrase',
        field: 'vrije tijd',
        level: 2,
        nl: 'We drinken koffie bij het meer.',
        sv: 'Vi fikar vid sjön.',
        why: 'Vid betekent "bij, aan". Sjön is de bepaalde vorm van en sjö.',
        accept: ['Vi dricker kaffe vid sjön.']
    },
    {
        id: 'ca-t-02',
        world: 'camper',
        slot: 8,
        kind: 'truefalse',
        field: 'bagage',
        level: 2,
        nl: 'We pakken de tent in de camper in.',
        sv: 'Vi packar tältet i kylskåpet.',
        isTrue: false,
        correction: 'Vi packar tältet i husbilen.',
        why: 'De tent past niet in de koelkast, hij gaat in de camper.',
        accept: []
    },
    {
        id: 'so-n-01',
        world: 'sanktolof',
        slot: 1,
        kind: 'noun',
        field: 'eten',
        level: 2,
        nl: 'de appel',
        sv: 'äpple',
        article: 'ett',
        definite: 'äpplet',
        plural: 'äpplen',
        why: 'Äpple is een ett-woord. Ett-woorden op -e krijgen in het meervoud -n: äpplen.',
        accept: []
    },
    {
        id: 'so-n-02',
        world: 'sanktolof',
        slot: 1,
        kind: 'noun',
        field: 'huis',
        level: 2,
        nl: 'het huis',
        sv: 'hus',
        article: 'ett',
        definite: 'huset',
        plural: 'hus',
        why: 'Hus is een ett-woord. Het meervoud is hetzelfde: ett hus, flera hus.',
        accept: []
    },
    {
        id: 'so-w-01',
        world: 'sanktolof',
        slot: 1,
        kind: 'word',
        field: 'werkwoord',
        level: 2,
        nl: 'wonen',
        sv: 'att bo',
        forms: { presens: 'bor', preteritum: 'bodde', supinum: 'bott' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'so-p-01',
        world: 'sanktolof',
        slot: 1,
        kind: 'phrase',
        field: 'plaats',
        level: 2,
        nl: 'We logeren in een huis in Sankt Olof.',
        sv: 'Vi bor i ett hus i Sankt Olof.',
        why: 'Bo betekent wonen, maar ook ergens verblijven. Hus is een ett-woord, dus ett hus.',
        accept: []
    },
    {
        id: 'so-n-03',
        world: 'sanktolof',
        slot: 2,
        kind: 'noun',
        field: 'natuur',
        level: 2,
        nl: 'de appelboom',
        sv: 'äppelträd',
        article: 'ett',
        definite: 'äppelträdet',
        plural: 'äppelträd',
        why: 'Äppelträd is een ett-woord. Het woord is samengesteld uit äpple en träd, en volgt träd: een ett-woord.',
        accept: []
    },
    {
        id: 'so-w-02',
        world: 'sanktolof',
        slot: 2,
        kind: 'word',
        field: 'vervoer',
        level: 2,
        nl: 'fietsen',
        sv: 'att cykla',
        forms: { presens: 'cyklar', preteritum: 'cyklade', supinum: 'cyklat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'so-g-01',
        world: 'sanktolof',
        slot: 2,
        kind: 'gap',
        field: 'werkwoord',
        level: 2,
        nl: 'We logeren in Sankt Olof.',
        sv: 'Vi ___ i Sankt Olof.',
        answer: 'bor',
        why: 'Bo betekent wonen, maar ook ergens verblijven. Het werkwoord verandert niet per persoon.',
        accept: []
    },
    {
        id: 'so-s-01',
        world: 'sanktolof',
        slot: 2,
        kind: 'silly',
        field: 'humor',
        level: 2,
        nl: 'De slak woont in een appel.',
        sv: 'Snigeln bor i ett äpple.',
        why: 'Een gekke zin met bekende woorden. Äpple is een ett-woord, dus ett äpple.',
        accept: []
    },
    {
        id: 'so-n-04',
        world: 'sanktolof',
        slot: 3,
        kind: 'noun',
        field: 'zee',
        level: 2,
        nl: 'het strand',
        sv: 'strand',
        article: 'en',
        definite: 'stranden',
        plural: 'stränder',
        why: 'Strand is een en-woord. Het meervoud krijgt een umlaut: stränder.',
        accept: []
    },
    {
        id: 'so-n-05',
        world: 'sanktolof',
        slot: 3,
        kind: 'noun',
        field: 'gebouw',
        level: 2,
        nl: 'de kerk',
        sv: 'kyrka',
        article: 'en',
        definite: 'kyrkan',
        plural: 'kyrkor',
        why: 'Kyrka is een en-woord. Bij en-woorden op -a wordt het meervoud -or: kyrkor.',
        accept: []
    },
    {
        id: 'so-f-01',
        world: 'sanktolof',
        slot: 3,
        kind: 'form',
        field: 'grammatica',
        level: 2,
        nl: 'ett äpple, meervoud',
        prompt: 'ett äpple, meervoud',
        answer: 'äpplen',
        why: 'Ett-woorden op -e krijgen in het meervoud -n: äpplen.',
        accept: []
    },
    {
        id: 'so-p-02',
        world: 'sanktolof',
        slot: 3,
        kind: 'phrase',
        field: 'beweging',
        level: 2,
        nl: 'Ik fiets naar de kerk.',
        sv: 'Jag cyklar till kyrkan.',
        why: 'Kyrkan is de bepaalde vorm van en kyrka. Till betekent "naar".',
        accept: []
    },
    {
        id: 'so-n-06',
        world: 'sanktolof',
        slot: 4,
        kind: 'noun',
        field: 'landbouw',
        level: 2,
        nl: 'het koolzaadveld',
        sv: 'rapsfält',
        article: 'ett',
        definite: 'rapsfältet',
        plural: 'rapsfält',
        why: 'Rapsfält is een ett-woord. Het meervoud is hetzelfde: ett rapsfält, flera rapsfält.',
        accept: []
    },
    {
        id: 'so-w-03',
        world: 'sanktolof',
        slot: 4,
        kind: 'word',
        field: 'plaats',
        level: 2,
        nl: 'liggen',
        sv: 'att ligga',
        forms: { presens: 'ligger', preteritum: 'låg', supinum: 'legat' },
        why: 'Ligga is onregelmatig: ligger, låg, legat.',
        accept: []
    },
    {
        id: 'so-g-02',
        world: 'sanktolof',
        slot: 4,
        kind: 'gap',
        field: 'voorzetsel',
        level: 2,
        nl: 'We fietsen naar het strand.',
        sv: 'Vi cyklar ___ stranden.',
        answer: 'till',
        why: '"Till" betekent "naar" en geeft een richting aan.',
        accept: []
    },
    {
        id: 'so-t-01',
        world: 'sanktolof',
        slot: 4,
        kind: 'truefalse',
        field: 'geografie',
        level: 2,
        nl: 'Sankt Olof ligt in Skåne.',
        sv: 'Sankt Olof ligger i Malmö.',
        isTrue: false,
        correction: 'Sankt Olof ligger i Skåne.',
        why: 'Sankt Olof ligt op Österlen in Skåne, niet in de stad Malmö.',
        accept: []
    },
    {
        id: 'so-n-07',
        world: 'sanktolof',
        slot: 5,
        kind: 'noun',
        field: 'zee',
        level: 2,
        nl: 'de zee',
        sv: 'hav',
        article: 'ett',
        definite: 'havet',
        plural: 'hav',
        why: 'Hav is een ett-woord. Het meervoud is hetzelfde: ett hav, flera hav.',
        accept: []
    },
    {
        id: 'so-n-08',
        world: 'sanktolof',
        slot: 5,
        kind: 'noun',
        field: 'eten',
        level: 2,
        nl: 'het brood',
        sv: 'bröd',
        article: 'ett',
        definite: 'brödet',
        plural: 'bröd',
        why: 'Bröd is een ett-woord. Het meervoud is hetzelfde: ett bröd, flera bröd.',
        accept: []
    },
    {
        id: 'so-b-01',
        world: 'sanktolof',
        slot: 5,
        kind: 'builder',
        field: 'vraagzin',
        level: 2,
        nl: 'Woon je in een huis?',
        sv: 'Bor du i ett hus?',
        pieces: ['Bor', 'du', 'i', 'ett', 'hus?'],
        why: 'Bij een ja/nee-vraag staat het werkwoord vooraan: Bor du?',
        accept: []
    },
    {
        id: 'so-w-04',
        world: 'sanktolof',
        slot: 5,
        kind: 'word',
        field: 'kleur',
        level: 2,
        nl: 'rood',
        sv: 'röd',
        why: 'Bij een ett-woord krijgt röd een -t: ett rött hus.',
        accept: []
    },
    {
        id: 'so-n-09',
        world: 'sanktolof',
        slot: 6,
        kind: 'noun',
        field: 'landbouw',
        level: 2,
        nl: 'de boerderij',
        sv: 'gård',
        article: 'en',
        definite: 'gården',
        plural: 'gårdar',
        why: 'Gård is een en-woord.',
        accept: []
    },
    {
        id: 'so-w-05',
        world: 'sanktolof',
        slot: 6,
        kind: 'word',
        field: 'keuken',
        level: 2,
        nl: 'bakken',
        sv: 'att baka',
        forms: { presens: 'bakar', preteritum: 'bakade', supinum: 'bakat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'so-s-02',
        world: 'sanktolof',
        slot: 6,
        kind: 'silly',
        field: 'humor',
        level: 2,
        nl: 'Cleo fietst met een appelboom naar de zee.',
        sv: 'Cleo cyklar till havet med ett äppelträd.',
        why: 'Een gekke zin met bekende woorden. Med betekent "met".',
        accept: []
    },
    {
        id: 'so-p-03',
        world: 'sanktolof',
        slot: 6,
        kind: 'phrase',
        field: 'tijd',
        level: 2,
        nl: 'Gisteren fietsten we naar de boerderij.',
        sv: 'Igår cyklade vi till gården.',
        why: 'Cyklade is de verleden tijd van cykla. Na igår komt het werkwoord op de tweede plek, voor vi.',
        accept: [
            'Vi cyklade till gården igår.',
            'I går cyklade vi till gården.',
            'Vi cyklade till gården i går.'
        ]
    },
    {
        id: 'so-n-10',
        world: 'sanktolof',
        slot: 7,
        kind: 'noun',
        field: 'seizoen',
        level: 2,
        nl: 'de zomer',
        sv: 'sommar',
        article: 'en',
        definite: 'sommaren',
        plural: 'somrar',
        why: 'Sommar is een en-woord. In het meervoud wordt de dubbele m een enkele m: somrar.',
        accept: []
    },
    {
        id: 'so-w-06',
        world: 'sanktolof',
        slot: 7,
        kind: 'word',
        field: 'oordeel',
        level: 2,
        nl: 'mooi',
        sv: 'vacker',
        why: 'Bij een ett-woord wordt vacker vackert: ett vackert hus.',
        accept: []
    },
    {
        id: 'so-g-03',
        world: 'sanktolof',
        slot: 7,
        kind: 'gap',
        field: 'bijvoeglijk naamwoord',
        level: 2,
        nl: 'Het huis is rood.',
        sv: 'Huset är ___.',
        answer: 'rött',
        why: 'Hus is een ett-woord, dus röd wordt rött.',
        accept: []
    },
    {
        id: 'so-f-02',
        world: 'sanktolof',
        slot: 7,
        kind: 'form',
        field: 'tijd',
        level: 2,
        nl: 'att bo, verleden tijd',
        prompt: 'att bo, verleden tijd',
        answer: 'bodde',
        why: 'Bo is een kort werkwoord: bor, bodde, bott.',
        accept: []
    },
    {
        id: 'so-n-11',
        world: 'sanktolof',
        slot: 8,
        kind: 'noun',
        field: 'eten',
        level: 2,
        nl: 'het koekje',
        sv: 'kaka',
        article: 'en',
        definite: 'kakan',
        plural: 'kakor',
        why: 'Kaka is een en-woord. Bij en-woorden op -a wordt het meervoud -or: kakor.',
        accept: []
    },
    {
        id: 'so-n-12',
        world: 'sanktolof',
        slot: 8,
        kind: 'noun',
        field: 'gebouw',
        level: 2,
        nl: 'de vuurtoren',
        sv: 'fyr',
        article: 'en',
        definite: 'fyren',
        plural: 'fyrar',
        why: 'Fyr is een en-woord.',
        accept: []
    },
    {
        id: 'so-p-04',
        world: 'sanktolof',
        slot: 8,
        kind: 'phrase',
        field: 'fika',
        level: 2,
        nl: 'We aten koekjes onder de appelboom.',
        sv: 'Vi åt kakor under äppelträdet.',
        why: 'Åt is de verleden tijd van äta. Äppelträdet is de bepaalde vorm van ett äppelträd.',
        accept: ['Under äppelträdet åt vi kakor.']
    },
    {
        id: 'so-t-02',
        world: 'sanktolof',
        slot: 8,
        kind: 'truefalse',
        field: 'geografie',
        level: 2,
        nl: 'Skåne ligt in Zweden.',
        sv: 'Skåne ligger i Sverige.',
        isTrue: true,
        correction: null,
        why: 'Skåne is het zuidelijkste landskap van Zweden.',
        accept: []
    },
    {
        id: 'ma-n-01',
        world: 'malmo',
        slot: 1,
        kind: 'noun',
        field: 'stad',
        level: 2,
        nl: 'de stad',
        sv: 'stad',
        article: 'en',
        definite: 'staden',
        plural: 'städer',
        why: 'Stad is een en-woord. Het meervoud krijgt een umlaut: städer.',
        accept: []
    },
    {
        id: 'ma-n-02',
        world: 'malmo',
        slot: 1,
        kind: 'noun',
        field: 'vervoer',
        level: 2,
        nl: 'het station',
        sv: 'station',
        article: 'en',
        definite: 'stationen',
        plural: 'stationer',
        why: 'Station is een en-woord. Het meervoud krijgt -er: stationer.',
        accept: []
    },
    {
        id: 'ma-w-01',
        world: 'malmo',
        slot: 1,
        kind: 'word',
        field: 'winkelen',
        level: 2,
        nl: 'kopen',
        sv: 'att köpa',
        forms: { presens: 'köper', preteritum: 'köpte', supinum: 'köpt' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'ma-p-01',
        world: 'malmo',
        slot: 1,
        kind: 'phrase',
        field: 'plaats',
        level: 2,
        nl: 'Nu zijn we in Malmö.',
        sv: 'Nu är vi i Malmö.',
        why: 'Na nu komt het werkwoord op de tweede plek, voor vi.',
        accept: ['Vi är i Malmö nu.']
    },
    {
        id: 'ma-n-03',
        world: 'malmo',
        slot: 2,
        kind: 'noun',
        field: 'bouwwerk',
        level: 2,
        nl: 'de brug',
        sv: 'bro',
        article: 'en',
        definite: 'bron',
        plural: 'broar',
        why: 'Bro is een en-woord. Het meervoud is broar.',
        accept: []
    },
    {
        id: 'ma-w-02',
        world: 'malmo',
        slot: 2,
        kind: 'word',
        field: 'sociaal',
        level: 2,
        nl: 'ontmoeten',
        sv: 'att träffa',
        forms: { presens: 'träffar', preteritum: 'träffade', supinum: 'träffat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'ma-g-01',
        world: 'malmo',
        slot: 2,
        kind: 'gap',
        field: 'bepaalde vorm',
        level: 2,
        nl: 'We rijden over de brug.',
        sv: 'Vi åker över ___.',
        answer: 'bron',
        why: 'Bron is de bepaalde vorm van en bro: de brug. Bij een en-woord op een klinker komt alleen -n.',
        accept: []
    },
    {
        id: 'ma-s-01',
        world: 'malmo',
        slot: 2,
        kind: 'silly',
        field: 'humor',
        level: 2,
        nl: 'De kat koopt een station in de stad.',
        sv: 'Katten köper en station i staden.',
        why: 'Een gekke zin met bekende woorden. Staden is de bepaalde vorm van en stad.',
        accept: []
    },
    {
        id: 'ma-n-04',
        world: 'malmo',
        slot: 3,
        kind: 'noun',
        field: 'water',
        level: 2,
        nl: 'het kanaal',
        sv: 'kanal',
        article: 'en',
        definite: 'kanalen',
        plural: 'kanaler',
        why: 'Kanal is een en-woord. Het meervoud krijgt -er: kanaler.',
        accept: []
    },
    {
        id: 'ma-n-05',
        world: 'malmo',
        slot: 3,
        kind: 'noun',
        field: 'plein',
        level: 2,
        nl: 'het plein',
        sv: 'torg',
        article: 'ett',
        definite: 'torget',
        plural: 'torg',
        why: 'Torg is een ett-woord. Het meervoud is hetzelfde: ett torg, flera torg.',
        accept: []
    },
    {
        id: 'ma-f-01',
        world: 'malmo',
        slot: 3,
        kind: 'form',
        field: 'grammatica',
        level: 2,
        nl: 'en stad, meervoud',
        prompt: 'en stad, meervoud',
        answer: 'städer',
        why: 'Stad krijgt in het meervoud -er en een umlaut: städer.',
        accept: []
    },
    {
        id: 'ma-p-02',
        world: 'malmo',
        slot: 3,
        kind: 'phrase',
        field: 'tijd',
        level: 2,
        nl: 'We ontmoetten een kat op het plein.',
        sv: 'Vi träffade en katt på torget.',
        why: 'Träffade is de verleden tijd van träffa. På betekent hier "op".',
        accept: ['På torget träffade vi en katt.']
    },
    {
        id: 'ma-n-06',
        world: 'malmo',
        slot: 4,
        kind: 'noun',
        field: 'vervoer',
        level: 3,
        nl: 'de bus',
        sv: 'buss',
        article: 'en',
        definite: 'bussen',
        plural: 'bussar',
        why: 'Buss is een en-woord.',
        accept: []
    },
    {
        id: 'ma-w-03',
        world: 'malmo',
        slot: 4,
        kind: 'word',
        field: 'modaal werkwoord',
        level: 3,
        nl: 'kunnen',
        sv: 'att kunna',
        forms: { presens: 'kan', preteritum: 'kunde', supinum: 'kunnat' },
        why: 'Na kan komt de infinitief zonder "att": jag kan cykla.',
        accept: []
    },
    {
        id: 'ma-g-02',
        world: 'malmo',
        slot: 4,
        kind: 'gap',
        field: 'grammatica',
        level: 3,
        nl: 'Ik kan fietsen.',
        sv: 'Jag ___ cykla.',
        answer: 'kan',
        why: 'Kan is "kan" en staat voor een infinitief zonder "att".',
        accept: []
    },
    {
        id: 'ma-t-01',
        world: 'malmo',
        slot: 4,
        kind: 'truefalse',
        field: 'geografie',
        level: 3,
        nl: 'Malmö ligt in Skåne.',
        sv: 'Malmö ligger i Skåne.',
        isTrue: true,
        correction: null,
        why: 'Malmö is de grootste stad van Skåne.',
        accept: []
    },
    {
        id: 'ma-n-07',
        world: 'malmo',
        slot: 5,
        kind: 'noun',
        field: 'horeca',
        level: 3,
        nl: 'het café',
        sv: 'café',
        article: 'ett',
        definite: 'caféet',
        plural: 'caféer',
        why: 'Café is een ett-woord. Het meervoud krijgt -er: caféer.',
        accept: []
    },
    {
        id: 'ma-n-08',
        world: 'malmo',
        slot: 5,
        kind: 'noun',
        field: 'natuur',
        level: 3,
        nl: 'het park',
        sv: 'park',
        article: 'en',
        definite: 'parken',
        plural: 'parker',
        why: 'Park is een en-woord.',
        accept: []
    },
    {
        id: 'ma-b-01',
        world: 'malmo',
        slot: 5,
        kind: 'builder',
        field: 'vraagzin',
        level: 3,
        nl: 'Kun je naar het park fietsen?',
        sv: 'Kan du cykla till parken?',
        pieces: ['Kan', 'du', 'cykla', 'till', 'parken?'],
        why: 'Bij een ja/nee-vraag staat het werkwoord vooraan: Kan du? De infinitief cykla komt later.',
        accept: []
    },
    {
        id: 'ma-w-04',
        world: 'malmo',
        slot: 5,
        kind: 'word',
        field: 'modaal werkwoord',
        level: 3,
        nl: 'willen',
        sv: 'att vilja',
        forms: { presens: 'vill', preteritum: 'ville', supinum: 'velat' },
        why: 'Na vill komt de infinitief zonder "att": jag vill cykla.',
        accept: []
    },
    {
        id: 'ma-n-09',
        world: 'malmo',
        slot: 6,
        kind: 'noun',
        field: 'eten',
        level: 3,
        nl: 'het ijsje',
        sv: 'glass',
        article: 'en',
        definite: 'glassen',
        plural: 'glassar',
        why: 'Glass is een en-woord. Let op: glass is ijs, geen drinkglas.',
        accept: []
    },
    {
        id: 'ma-w-05',
        world: 'malmo',
        slot: 6,
        kind: 'word',
        field: 'foto',
        level: 3,
        nl: 'fotograferen',
        sv: 'att fotografera',
        forms: { presens: 'fotograferar', preteritum: 'fotograferade', supinum: 'fotograferat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'ma-s-02',
        world: 'malmo',
        slot: 6,
        kind: 'silly',
        field: 'humor',
        level: 3,
        nl: 'Cleo wil een kanaal kopen.',
        sv: 'Cleo vill köpa en kanal.',
        why: 'Een gekke zin met bekende woorden. Na vill komt de infinitief köpa zonder "att".',
        accept: []
    },
    {
        id: 'ma-p-03',
        world: 'malmo',
        slot: 6,
        kind: 'phrase',
        field: 'tijd',
        level: 3,
        nl: 'Vandaag willen we ijs eten in het park.',
        sv: 'Idag vill vi äta glass i parken.',
        why: 'Na idag komt het werkwoord vill op de tweede plek, voor vi. Äta staat in de infinitief zonder "att".',
        accept: [
            'Vi vill äta glass i parken idag.',
            'I dag vill vi äta glass i parken.',
            'Vi vill äta glass i parken i dag.'
        ]
    },
    {
        id: 'ma-n-10',
        world: 'malmo',
        slot: 7,
        kind: 'noun',
        field: 'winkelen',
        level: 3,
        nl: 'de winkel',
        sv: 'butik',
        article: 'en',
        definite: 'butiken',
        plural: 'butiker',
        why: 'Butik is een en-woord.',
        accept: []
    },
    {
        id: 'ma-w-06',
        world: 'malmo',
        slot: 7,
        kind: 'word',
        field: 'prijs',
        level: 3,
        nl: 'duur',
        sv: 'dyr',
        why: 'Bij een ett-woord krijgt dyr een -t: ett dyrt äpple.',
        accept: []
    },
    {
        id: 'ma-g-03',
        world: 'malmo',
        slot: 7,
        kind: 'gap',
        field: 'bijvoeglijk naamwoord',
        level: 3,
        nl: 'De appel is duur.',
        sv: 'Äpplet är ___.',
        answer: 'dyrt',
        why: 'Äpple is een ett-woord, dus dyr wordt dyrt.',
        accept: []
    },
    {
        id: 'ma-f-02',
        world: 'malmo',
        slot: 7,
        kind: 'form',
        field: 'tijd',
        level: 3,
        nl: 'att köpa, verleden tijd',
        prompt: 'att köpa, verleden tijd',
        answer: 'köpte',
        why: 'Köpa krijgt -te in de verleden tijd: köpte.',
        accept: []
    },
    {
        id: 'ma-n-11',
        world: 'malmo',
        slot: 8,
        kind: 'noun',
        field: 'gebouw',
        level: 3,
        nl: 'de wolkenkrabber',
        sv: 'skyskrapa',
        article: 'en',
        definite: 'skyskrapan',
        plural: 'skyskrapor',
        why: 'Skyskrapa is een en-woord. Bij en-woorden op -a wordt het meervoud -or: skyskrapor.',
        accept: []
    },
    {
        id: 'ma-n-12',
        world: 'malmo',
        slot: 8,
        kind: 'noun',
        field: 'water',
        level: 3,
        nl: 'de haven',
        sv: 'hamn',
        article: 'en',
        definite: 'hamnen',
        plural: 'hamnar',
        why: 'Hamn is een en-woord.',
        accept: []
    },
    {
        id: 'ma-p-04',
        world: 'malmo',
        slot: 8,
        kind: 'phrase',
        field: 'bezienswaardigheid',
        level: 3,
        nl: 'Turning Torso is een wolkenkrabber in Malmö.',
        sv: 'Turning Torso är en skyskrapa i Malmö.',
        why: 'Är is "is". Skyskrapa is een en-woord, dus en skyskrapa.',
        accept: []
    },
    {
        id: 'ma-t-02',
        world: 'malmo',
        slot: 8,
        kind: 'truefalse',
        field: 'geografie',
        level: 3,
        nl: 'Turning Torso staat in Malmö.',
        sv: 'Turning Torso ligger i Amsterdam.',
        isTrue: false,
        correction: 'Turning Torso ligger i Malmö.',
        why: 'Turning Torso is de bekende wolkenkrabber van Malmö.',
        accept: []
    },
    {
        id: 'am-n-01',
        world: 'amsterdam',
        slot: 1,
        kind: 'noun',
        field: 'vervoer',
        level: 3,
        nl: 'de fiets',
        sv: 'cykel',
        article: 'en',
        definite: 'cykeln',
        plural: 'cyklar',
        why: 'Cykel is een en-woord. Het meervoud laat de e weg: cyklar.',
        accept: []
    },
    {
        id: 'am-n-02',
        world: 'amsterdam',
        slot: 1,
        kind: 'noun',
        field: 'planten',
        level: 3,
        nl: 'de tulp',
        sv: 'tulpan',
        article: 'en',
        definite: 'tulpanen',
        plural: 'tulpaner',
        why: 'Tulpan is een en-woord. Het meervoud krijgt -er: tulpaner.',
        accept: []
    },
    {
        id: 'am-w-01',
        world: 'amsterdam',
        slot: 1,
        kind: 'word',
        field: 'plaats',
        level: 3,
        nl: 'thuis (als je er al bent)',
        sv: 'hemma',
        why: 'Hemma betekent "thuis" als je er al bent. Ga je naar huis toe, dan zeg je hem.',
        accept: []
    },
    {
        id: 'am-p-01',
        world: 'amsterdam',
        slot: 1,
        kind: 'phrase',
        field: 'dieren',
        level: 3,
        nl: 'Nu is Cleo thuis.',
        sv: 'Nu är Cleo hemma.',
        why: 'Na nu komt het werkwoord är op de tweede plek, voor Cleo. Hemma betekent "thuis".',
        accept: ['Cleo är hemma nu.']
    },
    {
        id: 'am-n-03',
        world: 'amsterdam',
        slot: 2,
        kind: 'noun',
        field: 'eten',
        level: 3,
        nl: 'de kaas',
        sv: 'ost',
        article: 'en',
        definite: 'osten',
        plural: 'ostar',
        why: 'Ost is een en-woord.',
        accept: []
    },
    {
        id: 'am-w-02',
        world: 'amsterdam',
        slot: 2,
        kind: 'word',
        field: 'beweging',
        level: 3,
        nl: 'komen',
        sv: 'att komma',
        forms: { presens: 'kommer', preteritum: 'kom', supinum: 'kommit' },
        why: 'Komma is onregelmatig: kommer, kom, kommit.',
        accept: []
    },
    {
        id: 'am-g-01',
        world: 'amsterdam',
        slot: 2,
        kind: 'gap',
        field: 'plaats',
        level: 3,
        nl: 'Cleo wil naar huis komen.',
        sv: 'Cleo vill komma ___.',
        answer: 'hem',
        why: 'Hem gebruik je bij een beweging naar huis. Ben je er al, dan zeg je hemma.',
        accept: []
    },
    {
        id: 'am-s-01',
        world: 'amsterdam',
        slot: 2,
        kind: 'silly',
        field: 'humor',
        level: 3,
        nl: 'De tulp fietst naar het station.',
        sv: 'Tulpanen cyklar till stationen.',
        why: 'Een gekke zin met bekende woorden. Tulpanen en stationen zijn bepaalde vormen.',
        accept: []
    },
    {
        id: 'am-n-04',
        world: 'amsterdam',
        slot: 3,
        kind: 'noun',
        field: 'zoetigheid',
        level: 3,
        nl: 'de wafel',
        sv: 'våffla',
        article: 'en',
        definite: 'våfflan',
        plural: 'våfflor',
        why: 'Våffla is een en-woord. Bij en-woorden op -a wordt het meervoud -or: våfflor.',
        accept: []
    },
    {
        id: 'am-n-05',
        world: 'amsterdam',
        slot: 3,
        kind: 'noun',
        field: 'weer',
        level: 3,
        nl: 'de paraplu',
        sv: 'paraply',
        article: 'ett',
        definite: 'paraplyet',
        plural: 'paraplyer',
        why: 'Paraply is een ett-woord. Het meervoud krijgt -er: paraplyer.',
        accept: []
    },
    {
        id: 'am-f-01',
        world: 'amsterdam',
        slot: 3,
        kind: 'form',
        field: 'grammatica',
        level: 3,
        nl: 'att komma, verleden tijd',
        prompt: 'att komma, verleden tijd',
        answer: 'kom',
        why: 'Komma is onregelmatig. De verleden tijd is kom.',
        accept: []
    },
    {
        id: 'am-p-02',
        world: 'amsterdam',
        slot: 3,
        kind: 'phrase',
        field: 'tijd',
        level: 3,
        nl: 'Gisteren kwamen we thuis.',
        sv: 'Igår kom vi hem.',
        why: 'Na igår komt het werkwoord kom op de tweede plek, voor vi. Hem hoort bij een beweging naar huis.',
        accept: ['Vi kom hem igår.', 'I går kom vi hem.', 'Vi kom hem i går.']
    },
    {
        id: 'am-n-06',
        world: 'amsterdam',
        slot: 4,
        kind: 'noun',
        field: 'huis',
        level: 3,
        nl: 'het raam',
        sv: 'fönster',
        article: 'ett',
        definite: 'fönstret',
        plural: 'fönster',
        why: 'Fönster is een ett-woord. Het meervoud is hetzelfde: ett fönster, flera fönster.',
        accept: []
    },
    {
        id: 'am-w-03',
        world: 'amsterdam',
        slot: 4,
        kind: 'word',
        field: 'gevoel',
        level: 3,
        nl: 'verlangen (naar iets of iemand)',
        sv: 'att längta',
        forms: { presens: 'längtar', preteritum: 'längtade', supinum: 'längtat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'am-g-02',
        world: 'amsterdam',
        slot: 4,
        kind: 'gap',
        field: 'perfectum',
        level: 3,
        nl: 'We zijn thuisgekomen.',
        sv: 'Vi har ___ hem.',
        answer: 'kommit',
        why: 'Het perfectum is har + supinum. Het supinum van komma is kommit.',
        accept: []
    },
    {
        id: 'am-t-01',
        world: 'amsterdam',
        slot: 4,
        kind: 'truefalse',
        field: 'geografie',
        level: 3,
        nl: 'Amsterdam ligt in Nederland.',
        sv: 'Amsterdam ligger i Sverige.',
        isTrue: false,
        correction: 'Amsterdam ligger i Nederländerna.',
        why: 'Amsterdam ligt in Nederland (Nederländerna), niet in Zweden.',
        accept: []
    },
    {
        id: 'am-n-07',
        world: 'amsterdam',
        slot: 5,
        kind: 'noun',
        field: 'stad',
        level: 3,
        nl: 'de straat',
        sv: 'gata',
        article: 'en',
        definite: 'gatan',
        plural: 'gator',
        why: 'Gata is een en-woord. Bij en-woorden op -a wordt het meervoud -or: gator.',
        accept: []
    },
    {
        id: 'am-n-08',
        world: 'amsterdam',
        slot: 5,
        kind: 'noun',
        field: 'tijd',
        level: 3,
        nl: 'de nacht',
        sv: 'natt',
        article: 'en',
        definite: 'natten',
        plural: 'nätter',
        why: 'Natt is een en-woord. Het meervoud krijgt een umlaut: nätter.',
        accept: []
    },
    {
        id: 'am-b-01',
        world: 'amsterdam',
        slot: 5,
        kind: 'builder',
        field: 'woordvolgorde',
        level: 3,
        nl: 'Nu is Cleo thuisgekomen.',
        sv: 'Nu har Cleo kommit hem.',
        pieces: ['Nu', 'har', 'Cleo', 'kommit', 'hem.'],
        why: 'Het werkwoord staat op de tweede plek, dus har komt direct na nu. Kommit blijft achteraan.',
        accept: ['Cleo har kommit hem nu.']
    },
    {
        id: 'am-w-04',
        world: 'amsterdam',
        slot: 5,
        kind: 'word',
        field: 'gevoel',
        level: 3,
        nl: 'blij',
        sv: 'glad',
        why: 'Bij een ett-woord wordt glad glatt. In het meervoud wordt het glada.',
        accept: []
    },
    {
        id: 'am-n-09',
        world: 'amsterdam',
        slot: 6,
        kind: 'noun',
        field: 'huis',
        level: 3,
        nl: 'de bank',
        sv: 'soffa',
        article: 'en',
        definite: 'soffan',
        plural: 'soffor',
        why: 'Soffa is een en-woord. Bij en-woorden op -a wordt het meervoud -or: soffor.',
        accept: []
    },
    {
        id: 'am-w-05',
        world: 'amsterdam',
        slot: 6,
        kind: 'word',
        field: 'eigenschap',
        level: 3,
        nl: 'zacht',
        sv: 'mjuk',
        why: 'Bij een ett-woord wordt mjuk mjukt. Na den, det of in het meervoud wordt het mjuka.',
        accept: []
    },
    {
        id: 'am-s-02',
        world: 'amsterdam',
        slot: 6,
        kind: 'silly',
        field: 'humor',
        level: 3,
        nl: 'Cleo eet een paraplu.',
        sv: 'Cleo äter ett paraply.',
        why: 'Een gekke zin met bekende woorden. Paraply is een ett-woord, dus ett paraply.',
        accept: []
    },
    {
        id: 'am-p-03',
        world: 'amsterdam',
        slot: 6,
        kind: 'phrase',
        field: 'dieren',
        level: 3,
        nl: 'Cleo ligt op de zachte bank.',
        sv: 'Cleo ligger på den mjuka soffan.',
        why: 'Na "den" krijgt het bijvoeglijk naamwoord -a (mjuka) en het zelfstandig naamwoord de bepaalde vorm (soffan).',
        accept: []
    },
    {
        id: 'am-n-10',
        world: 'amsterdam',
        slot: 7,
        kind: 'noun',
        field: 'mensen',
        level: 3,
        nl: 'de familie',
        sv: 'familj',
        article: 'en',
        definite: 'familjen',
        plural: 'familjer',
        why: 'Familj is een en-woord. Het meervoud krijgt -er: familjer.',
        accept: []
    },
    {
        id: 'am-w-06',
        world: 'amsterdam',
        slot: 7,
        kind: 'word',
        field: 'gevoel',
        level: 3,
        nl: 'missen (iemand of iets missen)',
        sv: 'att sakna',
        forms: { presens: 'saknar', preteritum: 'saknade', supinum: 'saknat' },
        why: 'Een werkwoord in de infinitief heeft "att" ervoor.',
        accept: []
    },
    {
        id: 'am-g-03',
        world: 'amsterdam',
        slot: 7,
        kind: 'gap',
        field: 'bezit',
        level: 3,
        nl: 'Dat is mijn fiets.',
        sv: 'Det är ___ cykel.',
        answer: 'min',
        why: 'Cykel is een en-woord, dus min. Bij een ett-woord zeg je mitt.',
        accept: []
    },
    {
        id: 'am-f-02',
        world: 'amsterdam',
        slot: 7,
        kind: 'form',
        field: 'grammatica',
        level: 3,
        nl: 'ett fönster, bepaald',
        prompt: 'ett fönster, bepaald',
        answer: 'fönstret',
        why: 'Bij een ett-woord komt -et achter het woord. Bij fönster valt de e weg: fönstret.',
        accept: []
    },
    {
        id: 'am-n-11',
        world: 'amsterdam',
        slot: 8,
        kind: 'noun',
        field: 'denken',
        level: 3,
        nl: 'de herinnering',
        sv: 'minne',
        article: 'ett',
        definite: 'minnet',
        plural: 'minnen',
        why: 'Minne is een ett-woord. Ett-woorden op -e krijgen in het meervoud -n: minnen.',
        accept: []
    },
    {
        id: 'am-n-12',
        world: 'amsterdam',
        slot: 8,
        kind: 'noun',
        field: 'reizen',
        level: 3,
        nl: 'de reis',
        sv: 'resa',
        article: 'en',
        definite: 'resan',
        plural: 'resor',
        why: 'Resa is een en-woord. Bij en-woorden op -a wordt het meervoud -or: resor.',
        accept: []
    },
    {
        id: 'am-p-04',
        world: 'amsterdam',
        slot: 8,
        kind: 'phrase',
        field: 'terugblik',
        level: 3,
        nl: 'We hebben veel herinneringen aan de reis.',
        sv: 'Vi har många minnen från resan.',
        why: 'Många betekent "veel". Resan is de bepaalde vorm van en resa. Från betekent "van, uit".',
        accept: []
    },
    {
        id: 'am-t-02',
        world: 'amsterdam',
        slot: 8,
        kind: 'truefalse',
        field: 'verhaal',
        level: 3,
        nl: 'Cleo is thuisgekomen in Amsterdam.',
        sv: 'Cleo har kommit hem till Amsterdam.',
        isTrue: true,
        correction: null,
        why: 'Har kommit is het perfectum van komma. In het verhaal is Cleo weer thuis.',
        accept: []
    }
];

export const RIJTJES = [
    {
        id: 'rij-voornaamwoorden',
        title: 'Persoonlijke voornaamwoorden',
        world: 'volkstuin',
        rows: [
            ['jag', 'ik'],
            ['du', 'jij'],
            ['han', 'hij'],
            ['hon', 'zij (vrouw)'],
            ['den', 'het (bij een en-woord)'],
            ['det', 'het (bij een ett-woord)'],
            ['vi', 'wij'],
            ['ni', 'jullie'],
            ['de', 'zij (meervoud)']
        ]
    },
    {
        id: 'rij-vara',
        title: 'Vara (zijn)',
        world: 'volkstuin',
        rows: [
            ['att vara', 'zijn'],
            ['jag är', 'ik ben'],
            ['du är', 'jij bent'],
            ['han är', 'hij is'],
            ['hon är', 'zij is'],
            ['vi är', 'wij zijn'],
            ['ni är', 'jullie zijn'],
            ['de är', 'zij zijn'],
            ['jag var', 'ik was'],
            ['vi var', 'wij waren'],
            ['jag har varit', 'ik ben geweest']
        ]
    },
    {
        id: 'rij-ha',
        title: 'Ha (hebben)',
        world: 'volkstuin',
        rows: [
            ['att ha', 'hebben'],
            ['jag har', 'ik heb'],
            ['du har', 'jij hebt'],
            ['han har', 'hij heeft'],
            ['hon har', 'zij heeft'],
            ['vi har', 'wij hebben'],
            ['ni har', 'jullie hebben'],
            ['de har', 'zij hebben'],
            ['jag hade', 'ik had'],
            ['vi hade', 'wij hadden'],
            ['jag har haft', 'ik heb gehad']
        ]
    },
    {
        id: 'rij-getallen-1-10',
        title: 'Getallen 1 t/m 10',
        world: 'volkstuin',
        rows: [
            ['ett', '1'],
            ['två', '2'],
            ['tre', '3'],
            ['fyra', '4'],
            ['fem', '5'],
            ['sex', '6'],
            ['sju', '7'],
            ['åtta', '8'],
            ['nio', '9'],
            ['tio', '10']
        ]
    },
    {
        id: 'rij-dagen',
        title: 'Dagen van de week',
        world: 'volkstuin',
        rows: [
            ['måndag', 'maandag'],
            ['tisdag', 'dinsdag'],
            ['onsdag', 'woensdag'],
            ['torsdag', 'donderdag'],
            ['fredag', 'vrijdag'],
            ['lördag', 'zaterdag'],
            ['söndag', 'zondag']
        ]
    },
    {
        id: 'rij-getallen-11-20',
        title: 'Getallen 11 t/m 20',
        world: 'camper',
        rows: [
            ['elva', '11'],
            ['tolv', '12'],
            ['tretton', '13'],
            ['fjorton', '14'],
            ['femton', '15'],
            ['sexton', '16'],
            ['sjutton', '17'],
            ['arton', '18'],
            ['nitton', '19'],
            ['tjugo', '20']
        ]
    },
    {
        id: 'rij-vraagwoorden',
        title: 'Vraagwoorden',
        world: 'camper',
        rows: [
            ['vad', 'wat'],
            ['vem', 'wie'],
            ['var', 'waar'],
            ['vart', 'waarheen'],
            ['när', 'wanneer'],
            ['hur', 'hoe'],
            ['varför', 'waarom'],
            ['vilken', 'welke (bij een en-woord)'],
            ['vilket', 'welk (bij een ett-woord)'],
            ['vilka', 'welke (meervoud)']
        ]
    },
    {
        id: 'rij-voorzetsels',
        title: 'Plaatswoorden',
        world: 'camper',
        rows: [
            ['i', 'in'],
            ['på', 'op, aan'],
            ['under', 'onder'],
            ['över', 'boven, over'],
            ['bredvid', 'naast'],
            ['framför', 'voor'],
            ['bakom', 'achter'],
            ['mellan', 'tussen'],
            ['vid', 'bij, aan'],
            ['till', 'naar'],
            ['från', 'van, uit'],
            ['med', 'met']
        ]
    },
    {
        id: 'rij-sterke-werkwoorden-1',
        title: 'Sterke werkwoorden, deel 1',
        world: 'camper',
        rows: [
            ['att äta, äter, åt, ätit', 'eten'],
            ['att dricka, dricker, drack, druckit', 'drinken'],
            ['att se, ser, såg, sett', 'zien'],
            ['att gå, går, gick, gått', 'gaan, lopen'],
            ['att komma, kommer, kom, kommit', 'komen'],
            ['att sova, sover, sov, sovit', 'slapen'],
            ['att ligga, ligger, låg, legat', 'liggen'],
            ['att skriva, skriver, skrev, skrivit', 'schrijven']
        ]
    },
    {
        id: 'rij-kleuren',
        title: 'Kleuren (en, ett, meervoud)',
        world: 'sanktolof',
        rows: [
            ['röd, rött, röda', 'rood'],
            ['blå, blått, blå', 'blauw'],
            ['gul, gult, gula', 'geel'],
            ['grön, grönt, gröna', 'groen'],
            ['svart, svart, svarta', 'zwart'],
            ['vit, vitt, vita', 'wit'],
            ['grå, grått, grå', 'grijs'],
            ['brun, brunt, bruna', 'bruin']
        ]
    },
    {
        id: 'rij-min-din',
        title: 'Mijn en jouw',
        world: 'sanktolof',
        rows: [
            ['min katt', 'mijn kat'],
            ['mitt hus', 'mijn huis'],
            ['mina katter', 'mijn katten'],
            ['din katt', 'jouw kat'],
            ['ditt hus', 'jouw huis'],
            ['dina katter', 'jouw katten']
        ]
    },
    {
        id: 'rij-maanden',
        title: 'Maanden',
        world: 'sanktolof',
        rows: [
            ['januari', 'januari'],
            ['februari', 'februari'],
            ['mars', 'maart'],
            ['april', 'april'],
            ['maj', 'mei'],
            ['juni', 'juni'],
            ['juli', 'juli'],
            ['augusti', 'augustus'],
            ['september', 'september'],
            ['oktober', 'oktober'],
            ['november', 'november'],
            ['december', 'december']
        ]
    },
    {
        id: 'rij-sterke-werkwoorden-2',
        title: 'Sterke werkwoorden, deel 2',
        world: 'malmo',
        rows: [
            ['att ge, ger, gav, gett', 'geven'],
            ['att ta, tar, tog, tagit', 'nemen'],
            ['att sitta, sitter, satt, suttit', 'zitten'],
            ['att stå, står, stod, stått', 'staan'],
            ['att springa, springer, sprang, sprungit', 'rennen'],
            ['att bjuda, bjuder, bjöd, bjudit', 'trakteren, uitnodigen'],
            ['att få, får, fick, fått', 'krijgen, mogen'],
            ['att veta, vet, visste, vetat', 'weten']
        ]
    },
    {
        id: 'rij-regelmatige-werkwoorden',
        title: 'Regelmatige werkwoorden',
        world: 'malmo',
        rows: [
            ['att vattna, vattnar, vattnade, vattnat', 'water geven'],
            ['att cykla, cyklar, cyklade, cyklat', 'fietsen'],
            ['att baka, bakar, bakade, bakat', 'bakken'],
            ['att träffa, träffar, träffade, träffat', 'ontmoeten'],
            ['att köra, kör, körde, kört', 'rijden'],
            ['att köpa, köper, köpte, köpt', 'kopen'],
            ['att bo, bor, bodde, bott', 'wonen'],
            ['att läsa, läser, läste, läst', 'lezen']
        ]
    }
];
